#!/bin/bash

echo "🔐 PrivateVault Deployment Complete!"
echo "===================================="
echo ""
echo "📝 Deployed Contracts:"
echo "  MockUSDC:        0xE57f246BF27E79382C0E17222950415577eaCdBa"
echo "  PrivateVault:    0xe7eafC035Ee1149416B41EB3f1CB6dcFb517c8F2"
echo "  Oracle:          0xAd0799D4D6564c945C448D8BcFA890c41e111A98"
echo "  Network:         Tenderly Virtual Testnet"
echo ""
echo "🔐 Privacy Features Enabled:"
echo "  ✅ Commitment-based storage"
echo "  ✅ Encrypted credit scores"
echo "  ✅ Private loan amounts"
echo "  ✅ Zero-knowledge proofs"
echo "  ✅ Nullifier tracking"
echo "  ✅ Confidential transaction history"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Update contract addresses in your config:"
echo "   - Update src/lib/contract-addresses.json"
echo "   - Update PrivaCRE/my-workflow/config.staging.json"
echo ""
echo "2. The contracts are ready to use!"
echo "   - PrivateVault is deployed and functional"
echo "   - Oracle role is set to: 0xAd0799D4D6564c945C448D8BcFA890c41e111A98"
echo ""
echo "3. Test the deployment:"
echo "   npm run dev"
echo "   # Navigate to Dashboard → Run Analysis"
echo ""
echo "✅ Deployment Complete!"
